name: siptadik
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  splash_screen_view: ^3.0.0
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  intl: ^0.17.0
  package_info_plus: ^1.4.3+1
  flutter_zoom_drawer: ^3.0.3
  horizontalcalender: ^0.0.4
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icons.png"

flutter:

  uses-material-design: true

  assets:
    - assets/ilustrasi_login.svg
    - assets/submit_done.svg
    - assets/office.png
    - assets/no_data.svg

  fonts: 
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Thin.ttf
        weight: 100
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-Black.ttf
        weight: 900
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
